{% set name = "nidaqmx-python" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ni/nidaqmx-python/archive/{{ version }}.tar.gz
  sha256: e68c6cf0180fdd413a1ed43b278a2539cfb01f270ea6ad43c25a71dddc01cf54

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - six

test:
  imports:
    - nidaqmx

about:
  home: https://github.com/ni/nidaqmx-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python API for interacting with NI-DAQmx
  description: |
    The nidaqmx package contains an API (Application Programming Interface) for
    interacting with the NI-DAQmx driver. The package is implemented in Python.
    This package was created and is supported by NI. The package is implemented
    as a complex, highly object-oriented wrapper around the NI-DAQmx C API using
     the ctypes Python library.
  doc_url: http://nidaqmx-python.readthedocs.io/en/latest/
  dev_url: https://github.com/ni/nidaqmx-python

extra:
  recipe-maintainers:
    - carlodri
    - lstebel
