travis:
  secure:
    BINSTAR_TOKEN: VVWA5giAH3RaHtf05R/fmkLDdOKhCTDbyBmetQgnPMCUExOUYEozEqkBeGiblhXVQt2vwdGsxwKiiAJl/oQSOtIuozrfqxL4QMb01gzSAJ4TLV3f3VT8aTG5nJg53FqTyLzIY0v3JJvycdDK8Z3tbzUEcgiFDlfeGPbCXs8r34MFLkwrH/nb2xOceJPAmOI/dDfQVoTOGSCDSb6fyuvuiObD+ezZGY4tyk1W2BWk7p9ZX2js19Y/MGpZyjmHlPiERcWksNZ4gHh43awFnR74EWWS2epKlxZOuyI92FY2mFkAg0VrmT6a7ONqADrPAlinQAqkGYmD8EZ0qCma+zQptHSjxIcR1iuB7vV6z0RiiuqwN4hp5z/x0spwswOT43q/SHDQNIYFjubugWzVZurJlZZg2qRd4mRtYryBTW30ctP1+cbdcQHJSxcyWUG6/S4cCLWYs+FmnN0NMO0O0saeyPzB5IMR+OsaPHAKRMGPcsJVfUXIkVVHUwB/u4Ktq1+ChTqLMYCofPF3ndAqvhFGpEUPq5ABwmecSCIDk/snoivvXI3TuSse3v5PgHRi/CNgOUNqqk1UtyNe6sfQK6BltZRuQAUxOCbhngg3ldxg8OepyTOgj9yPfiOVNHbrYwjYfqhMltNQbOINrcgKIKXI6dn3X6lbpoAAjbnTP/CmsiQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
